<?php
/**
 * @file
 * f_content_type_news.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function f_content_type_news_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'node-news-body'
  $field_instances['node-news-body'] = array(
    'bundle' => 'news',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(
          'trim_length' => 600,
        ),
        'type' => 'text_summary_or_trimmed',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'body',
    'label' => 'Body',
    'required' => FALSE,
    'settings' => array(
      'display_summary' => TRUE,
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'module' => 'text',
      'settings' => array(
        'rows' => 20,
        'summary_rows' => 5,
      ),
      'type' => 'text_textarea_with_summary',
      'weight' => 2,
    ),
  );

  // Exported field_instance: 'node-news-field_content_main_image'
  $field_instances['node-news-field_content_main_image'] = array(
    'bundle' => 'news',
    'deleted' => 0,
    'description' => 'It is optional but VERY HIGHLY recommended that you add an image when creating this content. <br>
The image that you add here will be used in various places when listing this content. <br>
For eg: Latest Content Page, Facebook / Twitter shares etc.<br>
It is also HIGHLY RECOMMENDED that you upload an image that is roughly square (eg: 300x300 or 110x110 etc.)<br>
',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'image',
        'settings' => array(
          'image_link' => '',
          'image_style' => '',
        ),
        'type' => 'image',
        'weight' => 1,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_content_main_image',
    'label' => 'Content Main Image',
    'required' => 0,
    'settings' => array(
      'alt_field' => 1,
      'default_image' => 0,
      'file_directory' => 'content_main_image',
      'file_extensions' => 'png gif jpg jpeg',
      'max_filesize' => '',
      'max_resolution' => '',
      'min_resolution' => '',
      'title_field' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'image',
      'settings' => array(
        'preview_image_style' => 'thumbnail',
        'progress_indicator' => 'throbber',
      ),
      'type' => 'image_image',
      'weight' => 1,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Body');
  t('Content Main Image');
  t('It is optional but VERY HIGHLY recommended that you add an image when creating this content. <br>
The image that you add here will be used in various places when listing this content. <br>
For eg: Latest Content Page, Facebook / Twitter shares etc.<br>
It is also HIGHLY RECOMMENDED that you upload an image that is roughly square (eg: 300x300 or 110x110 etc.)<br>
');

  return $field_instances;
}
